version: "3.4"
services:
    postgres:
        build: 
            context: ./database
            args:
                - hostplatform=${HOST_PLATFORM}
                - pgversion=${PG_VERSION}
        image: postgres_img:test
        container_name: nobis_postgres_cont
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=${PGDATA}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes: 
            - pg_data:/var/lib/postgresql
            # In caso si voglia fare un dump iniziale va messo nella cartella ./database
            #- ./database/dump.sql:/docker-entrypoint-initdb.d/initDump.sql


# Create a volume to contain postgres data, kept safe by docker through the life cycle of the stack
# to inspect where the data is located use docker volume ls
volumes:
  pg_data: